import {
  Atom,
  Cat,
  Compass,
  Eclipse,
  Flame,
  Ghost,
  Globe,
  Hexagon,
  Moon,
  Orbit,
  Radiation,
  Rocket,
  Satellite,
  SatelliteDish,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sun,
  Telescope,
  Zap,
} from "lucide-react";

export const SPACE_ICONS = [
  { name: "Rocket", icon: Rocket },
  { name: "Star", icon: Star },
  { name: "Moon", icon: Moon },
  { name: "Sun", icon: Sun },
  { name: "Orbit", icon: Orbit },
  { name: "Satellite", icon: Satellite },
  { name: "SatelliteDish", icon: SatelliteDish },
  { name: "Telescope", icon: Telescope },
  { name: "Sparkles", icon: Sparkles },
  { name: "Globe", icon: Globe },
  { name: "Eclipse", icon: Eclipse },
  { name: "Compass", icon: Compass },
  { name: "Atom", icon: Atom },
  { name: "Flame", icon: Flame },
  { name: "Zap", icon: Zap },
  { name: "Shield", icon: Shield },
  { name: "Radiation", icon: Radiation },
  { name: "Hexagon", icon: Hexagon },
  { name: "Skull", icon: Skull },
  { name: "Ghost", icon: Ghost },
  { name: "Cat", icon: Cat },
] as const;

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> =
  Object.fromEntries(SPACE_ICONS.map(({ name, icon }) => [name, icon]));
